rest_adv/urls.py
from django.urls import path
from rest_adv import views

app_name = 'rest_adv'

urlpatterns = [
    path('', views.index, name='index'),
    path('restaurant/<slug:restaurant_name_slug>/',
        views.show_restaurant, name='show_restaurant'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('logout/', views.user_logout, name='logout'),
    path('restaurant/<slug:restaurant_name_slug>/add_review/', views.add_review, name='add_review'),
    path('add_restaurant/',views.add_restaurant,name='add_restaurant'),
    path('save_restaurant/',views.save_restaurant,name='save_restaurant'),
    path('search_restaurant',views.search_restaurant,name='search_restaurant'),
    path('update_my_profile',views.update_my_profile,name='update_my_profile'),
    path('my_collections',views.my_collections,name='my_collections'),
    path('my_reviews',views.my_reviews,name='my_reviews'),
    path('login_by_google',views.login_by_google,name='login_by_google'),
    path('category_restaurant/<str:category>/',views.category_restaurant,name='category_restaurant'),
]

restaurant_adviser/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rest_adv import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('rest_adv/', include('rest_adv.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant_adviser1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rest_adv import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('rest_adv/', include('rest_adv.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_adv/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=128, unique=True)
    rate = models.FloatField(default = 0)
    slug = models.SlugField(unique = True)

    # current categories:
    # chinese food
    # italian
    # sushi
    # fast food
    # snack
    # ice cream
    category = models.CharField(max_length=64, default='fast food') # everyone loves junk food :)

    intro = models.TextField(default = 'nothing yet')
    picture = models.ImageField(upload_to='restaurant_images', blank=True, default="statics/images/1.jpeg")

    createdAt = models.DateTimeField("Create time",auto_now_add=True)
    updatedAt = models.DateTimeField("Update time",auto_now=True)
    deletedAt = models.DateTimeField("Delete time",null=True,default=None)

    def delete(self, using=None, keep_parents=False):
        self.deletedAt = timezone.now()
        self.save()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Restaurant, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'restaurants'

    def __str__(self):
        return self.name


class Review(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.IntegerField(default = 0)
    message = models.TextField(default = 'nothing yet')

    createdAt = models.DateTimeField("Create time",auto_now_add=True)
    updatedAt = models.DateTimeField("Update time",auto_now=True)
    deletedAt = models.DateTimeField("Delete time",null=True,default=None)

    def delete(self, using=None, keep_parents=False):
        self.deletedAt = timezone.now()
        self.save()

    def __str__(self):
        return self.rate

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    like_restaurants = models.ManyToManyField('Restaurant')

    createdAt = models.DateTimeField("Create time",auto_now_add=True)
    updatedAt = models.DateTimeField("Update time",auto_now=True)
    deletedAt = models.DateTimeField("Delete time",null=True,default=None)

    def delete(self, using=None, keep_parents=False):
        self.deletedAt = timezone.now()
        self.save()

    def __str__(self):
        return self.user.username

rest_adv/forms.py
from django import forms
from django.contrib.auth.models import User
from rest_adv.models import UserProfile,Review,Restaurant

class ReviewForm(forms.ModelForm):
    # <input id="input-1" name="input-1" class="rating rating-loading" data-min="0" data-max="5" data-step="1">

    rate = forms.CharField(
        max_length=5,
        min_length=1,
        widget=forms.TextInput(attrs={
            'class':'rating rating-loading',
            'data-min':0,
            'data-max':5,
            'data-step':1,
            'type':'number'
        }))

    # bookname = forms.CharField(max_length=10,
    #                            min_length=5,
    #                            error_messages={
    #                                'required':u'书名不能为空',
    #                                'max_length':u'不能多余10个字',
    #                                'min_length':u'不能少于5个字',
    #                            },
    #                            widget=forms.TextInput(attrs={'class':'form-contorl','palceholder':u'标题不少于5字'}))
    message = forms.CharField()
    class Meta:
        model = Review
        fields = ('rate', 'message',)

class RestaurantForm(forms.ModelForm):
    name = forms.CharField(max_length=128,widget=forms.TextInput(attrs={'class':'form-control'}))
    rate = forms.FloatField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    intro = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Restaurant
        fields = ('name','picture','intro')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rest_adv/views.py
import json

from django.contrib.auth.models import User

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from rest_adv.models import Restaurant,Review,UserProfile

from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.core.files import File
from io import BytesIO
from urllib.request import urlopen

from rest_adv.forms import UserForm, UserProfileForm, ReviewForm, RestaurantForm

# Create your views here.
def index(request):
    context_dict = {}
    # get all restaurants
    context_dict['restaurants'] = Restaurant.objects.all().order_by('id')
    # get top 3 rate restaurants
    context_dict['top_restaurants'] = Restaurant.objects.all().order_by('-rate')[:3]

    # get first
    context_dict['first_restaurant'] = context_dict['top_restaurants'][0]
    return render(request,'rest_adv/index.html', context_dict)

def category_restaurant(request, category):
    context_dict={'restaurants':[],'search_text':category}
    try:
        restaurants = Restaurant.objects.filter(category=category)
        context_dict['restaurants'] = restaurants
        context_dict['top_restaurants'] = Restaurant.objects.all().order_by('-rate')[:3]
    except Restaurant.DoesNotExist:
        context_dict['restaurants'] = []
    return render(request, 'rest_adv/search_restaurant.html', context = context_dict)

def search_restaurant(request):
    search_text = request.GET.get('search_text')
    context_dict={'restaurants':[],'search_text':search_text}
    try:
        restaurants = Restaurant.objects.filter(intro__contains=search_text)
        context_dict['restaurants'] = restaurants

        context_dict['top_restaurants'] = Restaurant.objects.all().order_by('-rate')[:3]
    except Restaurant.DoesNotExist:
        context_dict['restaurants'] = []
    return render(request, 'rest_adv/search_restaurant.html', context = context_dict)

@login_required
def my_profile(request):
    context_dict = {}
    try:
        context_dict['user'] = request.user
    except Restaurant.DoesNotExist:
        context_dict['user'] = None
    return render(request, 'rest_adv/my_profile.html', context = context_dict)

@login_required
def update_my_profile(request):
    try:
        if request.method == 'POST':
            username = request.POST.get('username')
            website = request.POST.get('website')
            
            # request.user.like_restaurants.add(restaurant_id)
            current_user = request.user

            if current_user.username != username:
                current_user.username = username
                current_user.save()

            if 'picture' in request.FILES:
                current_user.profile.picture = request.FILES['picture']
                current_user.profile.save()
            
            if current_user.profile.website != website:
                current_user.profile.website = website
                current_user.profile.save()
            
    except Restaurant.DoesNotExist:
        pass
    return redirect(reverse('rest_adv:my_profile'))

@login_required
def my_collections(request):
    context_dict = {}
    try:
        context_dict['restaurants'] = request.user.profile.like_restaurants.all()
    except Restaurant.DoesNotExist:
        context_dict['restaurants'] = None
    return render(request, 'rest_adv/my_collections.html', context = context_dict)

@login_required
def my_reviews(request):
    context_dict = {}
    try:
        context_dict['reviews'] = Review.objects.filter(user=request.user)
    except Restaurant.DoesNotExist:
        context_dict['reviews'] = None
    return render(request, 'rest_adv/my_reviews.html', context = context_dict)

def show_restaurant(request, restaurant_name_slug):
    context_dict={}
    try:
        restaurant = Restaurant.objects.get(slug=restaurant_name_slug)
        context_dict['restaurant'] = restaurant
        reviews = Review.objects.filter(restaurant=restaurant)
        context_dict['reviews'] = reviews
    except Restaurant.DoesNotExist:
        context_dict['restaurant'] = None
    return render(request, 'rest_adv/restaurant.html', context = context_dict)

@login_required
def save_restaurant(request):
    try:
        if request.method == 'POST':
            # json_result = json.loads(request.body, strict=False)
            restaurant_id = request.POST.get('id')
            restaurant = Restaurant.objects.get(id=restaurant_id)
            
            # request.user.like_restaurants.add(restaurant_id)
            current_user = UserProfile.objects.get(user_id=request.user.id)

            if current_user.like_restaurants.filter(id=restaurant_id):
                result = {"status":"not post","data":"You have saved it~!"}
            else:
                current_user.like_restaurants.add(restaurant_id)
                result = {"status":"not post","data":"Saved success!"}

            # return success
            return JsonResponse(result,safe=False) 
        else:
            result = {"status":"not post","data":[request.body]}
            return JsonResponse(result,safe=False) 
    except Restaurant.DoesNotExist:
        # return error
        result = {"status":"error","data":""}
        return JsonResponse(result)


def login_by_google(request):
    if request.method == 'POST':
        google_id = request.POST.get('google_id')
        google_email = request.POST.get('google_email')
        google_profile_url = request.POST.get('google_profile_url')
        google_first_name = request.POST.get('google_first_name')
        google_last_name = request.POST.get('google_last_name')

        users = User.objects.filter(email=google_email)
        if users:
            # login with exists account
            login(request, users[0])
            result = {"status":"success","data":"User exists, login success!"}
            return JsonResponse(result,safe=False) 

        user = User()
        user.username = google_email
        user.email = google_email
        user.set_password('123456') # init password is 123456
        user.first_name = google_first_name
        user.last_name = google_last_name
        user.is_active = True
        user.save()

        profile = UserProfile(user=user)

        # get profile from google
        # r = urlopen(google_profile_url)
        # io = BytesIO(r.read())
        # result = profile.picture.save("{}_{}.jpg".format('test',int(time.time())), File(io))
        # profile.picture = google_profile_url
        profile.save()

        login(request, user)

        result = {"status":"success","data":"Login success!"+result}
        return JsonResponse(result,safe=False) 
    else:
        result = {"status":"error","data":"Not Post Method"}
        return JsonResponse(result,safe=False) 


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            #put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
                 'rest_adv/register.html',
                 context = {'user_form': user_form,
                            'profile_form': profile_form,
                            'registered': registered})


def user_login(request):
    context_dict = {}
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user

templates/rest_adv/base.html
<!DOCTYPE html> {% load staticfiles %}
<html>

<head>
    <meta charset="utf-8">

    <title>
        restaurant - {% block title_block %} How to Tango with Django! {% endblock %}
    </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/pricing/">

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- start rating plugin -->
    <link href="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/css/star-rating.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/js/star-rating.min.js"></script>

    <link href="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/themes/krajee-svg/theme.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/themes/krajee-svg/theme.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/themes/krajee-fas/theme.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/themes/krajee-fas/theme.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/themes/krajee-fa/theme.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap-star-rating/4.0.6/themes/krajee-fa/theme.min.js"></script>


    <!-- start rating plugin -->

    <style>
        /* nav */
        
        .l-nav {
            padding: 10px 40px;
            /* background-color: violet; */
            /* debug */
            display: flex;
            justify-content: space-between;
        }
        
        .m-nav__login {
            list-style: none;
            padding: 0;
            margin: 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .m-nav__loginli {
            padding-left: 20px;
            color: dimgray;
        }
        
        .m-nav__logina {
            text-decoration: none;
            color: dimgray;
            font-size: 18px;
        }
        /* nav */
        /* search */
        
        .l-search {
            display: flex;
            padding: 10px 40px;
            justify-content: center;
            align-items: center;
        }
        
        .m-search {
            background-color: gray;
        }
        
        .l-search__input {
            display: inline-block;
        }
        
        .m-search__input {
            width: 600px;
        }
        /* search */
        /* main body */
        
        .m-main-body {
            background-color: rgb(235, 235, 235);
        }
        
        .l-main-body {
            display: flex;
            justify-content: flex-start;
            margin-top: 16px;
            padding: 10px 40px;
        }
        /* main body */
        /* footer */
        
        .l-footer {
            display: flex;
            padding: 30px 40px;
            justify-content: space-between;
            align-items: center;
        }
        
        .m-footer {
            background-color: dimgrey;
        }
        
        .l-footer__copyright {
            margin-top: 10px;
        }
        
        .m-footer__copyright {
            color: floralwhite;
            font-size: 12px;
        }
        
        .l-footer__right {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .l-footer__resource {
            padding-left: 40px;
        }
        
        .m-footer__resourceh5 {
            color: floralwhite;
            font-size: 24px;
        }
        
        .m-footer__resourceul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        
        .m-footer__resourcea {
            text-decoration: none;
            color: gainsboro;
            font-size: 16px;
        }
        
        .m-footer__resourcea:hover {
            color: gainsboro;
        }
        /* footer */
    </style>

    {% block css_block %} {% endblock %}

</head>

<body>
    <div class="m-nav l-nav">
        <h5 class="m-nav__logo l-nav__logo">
            <a id="index-a" href="{% url 'rest_adv:index' %}">
                <img src={% static "images/logo.png" %} width="320px" height="75px" />
            </a>
        </h5>
        <ul class="m-nav__login l-nav__login">
            <li class="m-nav__loginli"><a class="m-nav__logina" href="{% url 'rest_adv:add_restaurant'%}">添加一个餐厅</a>
            </li>


            {% if user.is_authenticated %}
            <!-- Show these links when the user is logged in -->
            <li class="m-nav__loginli"><a class="m-nav__logina" href="{% url 'rest_adv:my_profile' %}">My Account</a></li>
            <li class="m-nav__loginli"><a class="m-nav__logina" href="{% url 'rest_adv:logout' %}">Logout</a></li>
            {% else %}
            <li class="m-nav__loginli"><a class="m-nav__logina" href="{% url 'rest_adv:register' %}">Sign Up</a></li>
            <li class="m-nav__loginli"><a class="m-nav__logina" href="{% url 'rest_adv:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>

    <div class="l-search m-search">
        <form class="l-search__form" method="get" action="/rest_adv/search_restaurant">
            {% csrf_token %}
            <input name="search_text" class="l-search__input m-search__input form-control" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>

    <div class="l-main-body m-main-body">
        {% block body_block %} {% endblock %}
    </div>


    <footer class="m-footer l-footer">
        <div class="l-footer__left">
            <a class="m-footer__logo" href="{% url 'rest_adv:index' %}">
                <img src={% static "images/logo.png" %} width="320px" height="75px" />
            </a>
            <div class="m-footer__copyright l-footer__copyright">
                © 2017-2019
            </div>
        </div>

        <div class="l-footer__right">
            <div class="m-footer__resource l-footer__resource">
                <h5 class="m-footer__resourceh5 l-footer__resourceh5">Resources</h5>
                <ul class="m-footer__resourceul l-footer__resourceul">
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Resource</a></li>
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Resource name</a></li>
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Another resource</a></li>
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Final resource</a></li>
                </ul>
            </div>

            <div class="m-footer__resource l-footer__resource">
                <h5 class="m-footer__resourceh5 l-footer__resourceh5">About</h5>
                <ul class="m-footer__resourceul l-footer__resourceul">
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Team</a></li>
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Locations</a></li>
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Privacy</a></li>
                    <li><a class="m-footer__resourcea l-footer__resourcea" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>



</body>
<script type="text/javascript ">
    $(".rating").rating();
</script>
{% block js_block %} {% endblock %}

</html>

templates/rest_adv/login.html
<!DOCTYPE html>
<meta name="google-signin-client_id" content="329317736900-nm6iha5dj81ochq5tjm4je4vn5nehmrh.apps.googleusercontent.com">

{% extends 'rest_adv/base.html' %} {% load staticfiles %} {% block title_block %} Login {% endblock %} {% block body_block %}

{% block css_block %}
<style>

</style>
{% endblock %}


<!-- <button type="button" onclick="signOut();">Sign out</button> -->

<div class="l-login m-login">
    <h1 class="l-login__h1 m-login__h1">Login to Restaurant Adviser</h1>
    {% if message %}
    <div class="alert alert-danger" role="alert">{{message}}</div>
    {% endif %}
    <form class="l-login__form m-login__form" id="login_form" method="post" action="{% url 'rest_adv:login' %}">
        {% csrf_token %}
        <label for="" class="l-login__label m-login__label" >Username</label>
        <input class="form-control" type="text" name="username" value="" size="50" />
        <label for="" class="l-login__label m-login__label" >Password</label>
        <input class="form-control" type="password" name="password" value="" size="50" />
        <input class="btn btn-default" type="submit" value="submit" style="display:  inline-block" />
    </form>
    <button id="customBtn" type="button" class="btn btn-danger" style="display:  inline-block" >Login By Google</button>
    <!-- <div id="my-signin2"></div> -->
    <!-- <div class="g-signin2" data-onsuccess="onSignIn"></div> -->
</div>
{% endblock %}

{% block js_block %}
<script src="https://apis.google.com/js/api:client.js"></script>
<script>
    var googleUser = {};
    var startApp = function() {
        gapi.load('auth2', function() {
            auth2 = gapi.auth2.init({
                client_id: '329317736900-nm6iha5dj81ochq5tjm4je4vn5nehmrh.apps.googleusercontent.com', //客户端ID
                cookiepolicy: 'single_host_origin',
                scope: 'profile' //可以请求除了默认的'profile' and 'email'之外的数据
            });
            attachSignin(document.getElementById('customBtn'));
        });
    };

    function attachSignin(element) {

        auth2.attachClickHandler(element, {},
            function(googleUser) {
                let profile = auth2.currentUser.get().getBasicProfile();


                console.log('ID: ' + profile.getId());
                console.log('Full Name: ' + profile.getName());
                console.log('Given Name: ' + profile.getGivenName());
                console.log('Family Name: ' + profile.getFamilyName());
                console.log('Image URL: ' + profile.getImageUrl());
                console.log('Email: ' + profile.getEmail());

                // register and login
                let csrf = $('input[name="csrfmiddlewaretoken"]').val();
                console.log('saving restaurant ...');
                let url = "{% url 'rest_adv:login_by_google' %}"

                $.ajax({
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': csrf,
                        'google_id': profile.getId(),
                        'google_email': profile.getEmail(),
                        'google_profile_url': profile.getImageUrl(),
                        'google_first_name': profile.getGivenName(),
                        'google_last_name': profile.getFamilyName(),
                    },
                    type: 'post',
                    cache: false,
                    dataType: 'json',
                    success: function(data) {
                        console.log(data);
                        alert(data.data);
                        console.log($('#index-a'));
                        $('#index-a')[0].click();
                    },
                    error: function() {
                        // view("异常！");    
                        alert("Error!");
                    }
                });
            },
            function(error) {
                console.log(JSON.stringify(error, undefined, 2));
            });
    }
    function onFailure(error) {
      console.log(error);
    }
    // function renderButton() {
    //   gapi.signin2.render('my-signin2', {
    //     'scope': 'profile email',
    //     'width': 240,
    //     'height': 50,
    //     'longtitle': true,
    //     'theme': 'dark',
    //     'onsuccess': onSuccess,
    //     'onfailure': onFailure
    //   });
    // }

    // function attachSignin(element) {
    //     auth2.attachClickHandler(element, {},
    //         function(googleUser) {
    //             var profile = auth2.currentUser.get().getBasicProfile();

    //             console.log('ID: ' + profile.getId());
    //             console.log('Full Name: ' + profile.getName());
    //             console.log('Given Name: ' + profile.getGivenName());
    //             console.log('Family Name: ' + profile.getFamilyName());
    //             console.log('Image URL: ' + profile.getImageUrl());
    //             console.log('Email: ' + profile.getEmail());

                
    //         },
    //         function(error) {
    //             console.log(JSON.stringify(error, undefined, 2));
    //         });
    // }
    startApp();

    //注销
    function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function() {
            alert('用户注销成功');
        });
    }

</script>
<!-- <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script> -->
<!-- <script src="https://apis.google.com/js/platform.js" async defer></script> -->
{% endblock %}

templates/rest_adv/register_old.html
<!DOCTYPE html>
{% extends 'rest_adv/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Restaurant Advisor</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rest_adv:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rest_adv:register' %}"
              enctype="multipart/form-data">
            {% csrf_token %}

        <!-- Display each form -->
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}